colocation: use gix for toggling `core.bare` config
Instead of forking a git process, use `gix` to toggle `core.bare` config.

The original `git -C <repo_root>/.jj/repo/store/git config repo.bare
<true|false>` fails when the user has `safe.bareRepository` config set to
'explicit'. A typical failure looks like this:

	% jj git colocation disable
	Error: Failed to set core.bare to true in Git config.
	Caused by: Git config failed: fatal: not in a git directory

.git is moved to .jj/repo/store/git as a bare repo, and if we run git directly:
	
	% git -C .jj/repo/store/git config repo.bare true
	fatal: not in a git directory

	% git -C .jj/repo/store/git status
	fatal: cannot use bare repository
	<repo_root>/.jj/repo/store/git (safe.bareRepository is 'explicit')

Use `gix` to avoid forking git and being interferred by git's configs.