docs workflow: try to fix it again
It's been broken since 514a009. Since 0e2d079,
the error was:

```
error: failed to push branch gh-pages to origin:
"fatal: could not read Username for 'https://github.com': No such device or address"
```

This is hard to test outside of prod, but follows a guess after
reading some Github docs and `gh auth login` docs from
<https://cli.github.com/manual/gh_auth_login>. I could not
find docs specifically about using the `git` CLI, but I'm guessing
that if `gh auth login` makes `git push` work on user machines by
setting `GH_TOKEN`, doing the same might help.

🤞

Cc @thoughtpolice, @martinvonz